const emojis = {
  blush: '😊',
  cat: '🐈',
  dog_face: '🐶',
  dogface: '🐶',
  dog: '🐕',
  doggo: '🐕',
  domestic_cat: '🐈',
  eye_roll: '🙄',
  eyeroll: '🙄',
  face_with_rolling_eyes: '🙄',
  facewithrollingeyes: '🙄',
  feline: '🐈',
  fire: '🔥',
  flame: '🔥',
  grapes: '🍇',
  heart: '❤️',
  heart_eyes: '😍',
  heart_face: '😍',
  hot: '🔥',
  housecat: '🐈',
  lit: '🔥',
  love_heart: '❤️',
  poop: '💩',
  shrug: '🤷',
  shrugging: '🤷',
  smile: '😀',
  smirk: '😏',
  thinking: '🤔',
  thinking_face: '🤔',
  thinkingface: '🤔',
  thumbs_down: '👎',
  thumbsdown: '👎',
  thumbs_up: '👍',
  thumbsup: '👍',
  wink: '😉'
}

module.exports = emojis
