const animalEmojis = {
  ant: '🐜',
  bug: '🐛',
  camel: '🐪',
  cat: '🐈',
  chicken: '🐔',
  dog_face: '🐶',
  dogface: '🐶',
  dog: '🐕',
  doggo: '🐕',
  domestic_cat: '🐈',
  domesticcat: '🐈',
  elephant: '🐘',
  feline: '🐈',
  horse: '🐎',
  housecat: '🐈',
  koala: '🐨',
  monkey: '🐒',
  monkey_face: '🐵',
  monkeyface: '🐵',
  mouse: '🐁',
  ox: '🐂',
  rabbit: '🐇',
  snake: '🐍',
  spider: '🕷️',
  turkey: '🦃',
  turtle: '🐢',
  whale: '🐋'
}

module.exports = animalEmojis
