const foodEmojis = {
  banana: '🍌',
  bread: '🍞',
  burger: '🍔',
  cantaloupe: '🍈',
  cheese: '🧀',
  cheese_wedge: '🧀',
  cheeseburger: '🍔',
  cheesewedge: '🧀',
  croissant: '🥐',
  grape: '🍇',
  grapes: '🍇',
  hamburger: '🍔',
  honeydew: '🍈',
  hot_dog: '🌭',
  hotdog: '🌭',
  lemon: '🍋',
  lemonade: '🍋',
  load_of_bread: '🍞',
  loadofbread: '🍞',
  mandarin: '🍊',
  melon: '🍈',
  muskmelon: '🍈',
  orange: '🍊',
  pancakes: '🥞',
  pineapple: '🍍',
  plantain: '🍌',
  rockmelon: '🍈',
  sausage: '🌭',
  taco: '🌮',
  tangerine: '🍊',
  watermelon: '🍉',
  yellow_fruit: '🍋',
  yellowfruit: '🍋'
}

module.exports = foodEmojis
